version: 2

project_name: openilink-hub

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    binary: oih
    goos: [linux]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CGO_CFLAGS=-Wno-stringop-overread -Wno-constant-conversion
    ldflags: &ldflags
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

  - id: linux-arm64
    binary: oih
    goos: [linux]
    goarch: [arm64]
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CGO_CFLAGS=-Wno-stringop-overread -Wno-constant-conversion
    ldflags: *ldflags

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt
  extra_files:
    - glob: darwin-archives/*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: xzwork
    name: openilink-hub
  extra_files:
    - glob: darwin-archives/*

dockers:
  - image_templates:
      - "ghcr.io/xzwork/openilink-hub:{{ .Version }}-amd64"
      - "docker.io/xzwork/openilink-hub:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.source=https://github.com/xzwork/openilink-hub"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    ids: [linux-amd64]
  - image_templates:
      - "ghcr.io/xzwork/openilink-hub:{{ .Version }}-arm64"
      - "docker.io/xzwork/openilink-hub:{{ .Version }}-arm64"
    use: buildx
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.source=https://github.com/xzwork/openilink-hub"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    ids: [linux-arm64]
    goarch: arm64
docker_manifests:
  - name_template: "ghcr.io/xzwork/openilink-hub:{{ .Version }}"
    image_templates:
      - "ghcr.io/xzwork/openilink-hub:{{ .Version }}-amd64"
      - "ghcr.io/xzwork/openilink-hub:{{ .Version }}-arm64"
  - name_template: "ghcr.io/xzwork/openilink-hub:latest"
    image_templates:
      - "ghcr.io/xzwork/openilink-hub:{{ .Version }}-amd64"
      - "ghcr.io/xzwork/openilink-hub:{{ .Version }}-arm64"
  - name_template: "docker.io/xzwork/openilink-hub:{{ .Version }}"
    image_templates:
      - "docker.io/xzwork/openilink-hub:{{ .Version }}-amd64"
      - "docker.io/xzwork/openilink-hub:{{ .Version }}-arm64"
  - name_template: "docker.io/xzwork/openilink-hub:latest"
    image_templates:
      - "docker.io/xzwork/openilink-hub:{{ .Version }}-amd64"
      - "docker.io/xzwork/openilink-hub:{{ .Version }}-arm64"
