version: 2

project_name: openilink-hub

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    binary: oih
    goos: [linux]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CGO_CFLAGS=-Wno-stringop-overread -Wno-constant-conversion
    ldflags: &ldflags
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt
  extra_files:
    - glob: darwin-archives/*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: xzwork
    name: openilink-hub
  extra_files:
    - glob: darwin-archives/*
